# Generated by Django 4.2.7 on 2023-11-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_splitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_splitter.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_splitter.person')),
            ],
        ),
        migrations.CreateModel(
            name='BillParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_share', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_splitter.bill')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_splitter.person')),
            ],
            options={
                'unique_together': {('bill', 'person')},
            },
        ),
    ]
